### ISSUE TITLE
json_decode error: Syntax error

### ISSUE THREAD

**Issue by lengjunbin-trec** [centrifugal/phpcent#62]
I use lumen framework to install this package with `5.1.0` version.
lumen framework is 10.0.
when I try run this code on my local.
`$client = new \phpcent\Client(env('CENTRIFUGO_BROADCAST_URL'), env('CENTRIFUGO_API_KEY'), env('CENTRIFUGO_HMAC_SECRET'));`
`$client->publish("channel-xxxxxx", ["message" => "Hello World"]);`
  it throw error
        `[2024-05-07 05:26:47] local.ERROR: json_decode error: Syntax error {"exception":"[object] (Exception(code: 0): json_decode error: Syntax error at /Users/a10116679/Desktop/project/lumenProject/vendor/centrifugal/phpcent/src/Client.php:389)
[stacktrace]
#0 /Users/a10116679/Desktop/project/lumenProject/vendor/centrifugal/phpcent/src/Client.php(144): phpcent\\Client->send('publish', Array)
#1 /Users/a10116679/Desktop/project/lumenProject/app/Http/Controllers/RetailerSmartCartController.php(41): phpcent\\Client->publish('cart_channel_na...', Array)
#2 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/container/BoundMethod.php(36): App\\Http\\Controllers\\RetailerSmartCartController->adb(Object(App\\Http\\Requests\\Api\\AdbRequest))
#3 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#6 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#7 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)
#8 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(356): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#9 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(331): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\RetailerSmartCartController), 'adb', Array)
#10 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)
#11 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(264): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#12 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#13 /Users/a10116679/Desktop/project/lumenProject/vendor/stancl/tenancy/src/Middleware/IdentificationMiddleware.php(36): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#14 /Users/a10116679/Desktop/project/lumenProject/vendor/stancl/tenancy/src/Middleware/InitializeTenancyByRequestData.php(46): Stancl\\Tenancy\\Middleware\\IdentificationMiddleware->initializeTenancy(Object(Laravel\\Lumen\\Http\\Request), Object(Closure), '867b8fb34b15403...')
#15 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/pipeline/Pipeline.php(183): Stancl\\Tenancy\\Middleware\\InitializeTenancyByRequestData->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#16 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#17 /Users/a10116679/Desktop/project/lumenProject/vendor/illuminate/pipeline/Pipeline.php(119): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#18 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(263): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#20 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#21 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(431): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#22 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#23 /Users/a10116679/Desktop/project/lumenProject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)
#24 /Users/a10116679/Desktop/project/lumenProject/public/index.php(28): Laravel\\Lumen\\Application->run()
#25 {main}
"} `

**Comment by lengjunbin-trec** [comment]
solved
